Repository AY2425S2-CS2113-W13-3/tp, pull requests merged in 2025-03, with the labels that each got.

#23 Feature: Income & Expense
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/finbro/FinBro.java
  src/main/java/seedu/finbro/logic/command/ClearCommand.java
  src/main/java/seedu/finbro/logic/command/Command.java
  src/main/java/seedu/finbro/logic/command/ExitCommand.java
  src/main/java/seedu/finbro/logic/command/ExpenseCommand.java
  src/main/java/seedu/finbro/logic/command/ExportCommand.java
  src/main/java/seedu/finbro/logic/command/HelpCommand.java
  src/main/java/seedu/finbro/logic/command/IncomeCommand.java
  src/main/java/seedu/finbro/logic/command/InvalidCommand.java
  src/main/java/seedu/finbro/logic/command/UnknownCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/Expense.java
  src/main/java/seedu/finbro/model/Income.java
  src/main/java/seedu/finbro/model/Transaction.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/storage/Storage.java
  src/main/java/seedu/finbro/ui/Ui.java
  src/test/java/seedu/finbro/FinBroTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#26 UiTest
  src/test/java/seedu/finbro/UiTest.java
Labels: type.Task

#27 Other: Make-up PR
  README.md
  src/test/java/seedu/finbro/FinBroTest.java
Labels: type.Task

#32 Others: Makeup PR
  src/test/java/seedu/finbro/FinBroTest.java
Labels: type.Task

#30 Adds IncomeCommandTest v1.0
  data/finbro.txt
  src/main/java/seedu/finbro/ui/Ui.java
  src/test/java/seedu/finbro/IncomeCommandTest.java
Labels: type.Task

#34 Add sample test
  src/test/java/seedu/finbro/FinBroTest.java
Labels: type.Task

#35 Branch listCommand
  src/main/java/seedu/finbro/logic/command/ListCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
Labels: priority.High

#36 Testing and Logging
  data/finbro.txt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/seedu/finbro/FinBro.java
  src/main/java/seedu/finbro/LoggingConfig.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/storage/Storage.java
  src/main/java/seedu/finbro/ui/Ui.java
  src/main/resources/logging.properties
  src/test/java/seedu/finbro/logic/command/IncomeCommandTest.java
  src/test/java/seedu/finbro/model/TransactionManagerTest.java
  src/test/java/seedu/finbro/model/TransactionTest.java
  src/test/java/seedu/finbro/ui/UiTest.java
Labels: type.Task

#38 Feature: View Balance
  src/main/java/seedu/finbro/logic/command/BalanceCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/test/java/seedu/finbro/logic/command/BalanceCommandTest.java
Labels: type.Task, priority.High

#41 Asserts
  src/main/java/seedu/finbro/logic/command/ExpenseCommand.java
  src/main/java/seedu/finbro/logic/command/ExportCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/Expense.java
  src/main/java/seedu/finbro/model/Income.java
  src/main/java/seedu/finbro/model/Transaction.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/storage/Storage.java
Labels: type.Enhancement

#44 Missing summary
  src/main/java/seedu/finbro/logic/parser/Parser.java
Labels: type.Bug

#46 Feature: EditCommand
  src/main/java/seedu/finbro/logic/command/EditCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/test/java/seedu/finbro/logic/command/EditCommandTest.java
Labels: type.Task, priority.High

#48 Basic Features Enhancement
  README.md
  docs/DeveloperGuide.md
  docs/README.md
  src/main/java/seedu/finbro/LoggingConfig.java
  src/main/java/seedu/finbro/logic/command/DeleteCommand.java
  src/main/java/seedu/finbro/logic/command/EditCommand.java
  src/main/java/seedu/finbro/logic/command/FilterCommand.java
  src/main/java/seedu/finbro/logic/command/ListCommand.java
  src/main/java/seedu/finbro/logic/command/SummaryCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/Expense.java
  src/main/java/seedu/finbro/model/Income.java
  src/main/java/seedu/finbro/model/Transaction.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/storage/Storage.java
  src/main/resources/logging.properties
  src/test/java/seedu/finbro/FinBroTest.java
  src/test/java/seedu/finbro/LoggingConfigTest.java
  src/test/java/seedu/finbro/logic/command/DeleteCommandTest.java
  src/test/java/seedu/finbro/logic/command/ExitCommandTest.java
  src/test/java/seedu/finbro/logic/command/ExpenseCommandTest.java
  src/test/java/seedu/finbro/logic/command/ExportCommandTest.java
  src/test/java/seedu/finbro/logic/command/FilterCommandTest.java
  src/test/java/seedu/finbro/logic/command/HelpCommandTest.java
  src/test/java/seedu/finbro/logic/command/InvalidCommandTest.java
  src/test/java/seedu/finbro/logic/command/ListCommandTest.java
  src/test/java/seedu/finbro/logic/command/SearchCommandTest.java
  src/test/java/seedu/finbro/logic/command/SummaryCommandTest.java
  src/test/java/seedu/finbro/model/ExpenseTest.java
  src/test/java/seedu/finbro/model/IncomeTest.java
  src/test/java/seedu/finbro/model/TransactionManagerTest.java
  src/test/java/seedu/finbro/model/TransactionTest.java
  src/test/java/seedu/finbro/parser/ParserTest.java
  src/test/java/seedu/finbro/storage/StorageTest.java
  src/test/java/seedu/finbro/ui/UiTest.java
Labels: type.Enhancement

#49 Hot Fix
  README.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement

#51 Logging and assertions: FilterCommand & SummaryCommand
  src/main/java/seedu/finbro/logic/command/FilterCommand.java
  src/main/java/seedu/finbro/logic/command/SummaryCommand.java
Labels: priority.High

#52 adds tests for duplicate check when creating new income / expense transaction
  src/main/java/seedu/finbro/logic/command/ExpenseCommand.java
  src/main/java/seedu/finbro/logic/command/IncomeCommand.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/test/java/seedu/finbro/logic/command/ExpenseCommandTest.java
  src/test/java/seedu/finbro/logic/command/IncomeCommandTest.java
  src/test/java/seedu/finbro/logic/command/SearchCommandTest.java
Labels: type.Task, priority.High

#73 Fixes annoying github gradle issues
  .github/workflows/gradle.yml
  src/main/java/seedu/finbro/FinBro.java
  src/main/java/seedu/finbro/logic/command/HelpCommand.java
  src/test/java/seedu/finbro/logic/command/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#75 adds valuable assertion
  src/main/java/seedu/finbro/model/TransactionManager.java
Labels: type.Enhancement

#74 Add date of creation to list command and update ListCommandTest
  src/main/java/seedu/finbro/logic/command/ListCommand.java
  src/test/java/seedu/finbro/logic/command/ListCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.Medium

#76 Enables assertions for gradle
  build.gradle
Labels: type.Task

#77 DG and code contributions~
  docs/DeveloperGuide.md
  src/test/java/seedu/finbro/FinBroTest.java
Labels: type.Enhancement

#79 Add friendly CLI for List Command
  src/main/java/seedu/finbro/logic/command/HelpCommand.java
  src/main/java/seedu/finbro/logic/command/ListCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/ui/Ui.java
Labels: priority.High

#81 Add friendly CLI for Delete Command.
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/ui/Ui.java
Labels: priority.High

#82 Add loggers for parseDeleteCommand
  src/main/java/seedu/finbro/logic/parser/Parser.java
Labels: priority.Medium

#83 adds parseCategory + makes income.execute and expense.execute ONE COMMAND ONE ACTION
  .gitignore
  src/main/java/seedu/finbro/logic/command/HelpCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/Expense.java
  src/main/java/seedu/finbro/ui/Ui.java
  src/test/java/seedu/finbro/logic/command/HelpCommandTest.java
  src/test/java/seedu/finbro/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#85 Add parseInteger and parseTag
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/ui/Ui.java
Labels: priority.High

#86 Update DG
  docs/DeveloperGuide.md
Labels: type.Task

#89 Add parseAmount that reads from UI
  src/main/java/seedu/finbro/logic/parser/Parser.java
Labels: priority.High

#91 Add budget setting that shows in summary
  src/main/java/seedu/finbro/FinBro.java
  src/main/java/seedu/finbro/logic/command/SetBudgetCommand.java
  src/main/java/seedu/finbro/logic/command/SummaryCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/storage/Storage.java
  src/main/java/seedu/finbro/ui/Ui.java
Labels: priority.High

#92 Minor UG change and PPP
  docs/UserGuide.md
  docs/img/FinBro.png
  docs/team/alan.md
Labels: type.Enhancement

#94 Changed ppp file naming to be detected by system
  docs/AboutUs.md
  docs/team/alaneel.md
  docs/team/denzelloke.md
  docs/team/laitcanard05.md
  docs/team/ljunfun.md
  docs/team/notgiggs.md
Labels: type.Enhancement

#96 Add delete range
  src/main/java/seedu/finbro/logic/command/DeleteCommand.java
  src/main/java/seedu/finbro/logic/command/SummaryCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/ui/Ui.java
  src/test/java/seedu/finbro/logic/command/DeleteCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#98 Adds Features to Milestone2.0
  src/main/java/seedu/finbro/FinBro.java
  src/main/java/seedu/finbro/LoggingConfig.java
  src/main/java/seedu/finbro/logic/command/EditCommand.java
  src/main/java/seedu/finbro/logic/command/ExitCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/main/java/seedu/finbro/ui/Ui.java
  src/test/java/seedu/finbro/LoggingConfigTest.java
  src/test/java/seedu/finbro/logic/command/EditCommandTest.java
  src/test/java/seedu/finbro/logic/command/ExitCommandTest.java
  src/test/java/seedu/finbro/logic/command/SetBudgetCommandTest.java
  src/test/java/seedu/finbro/logic/command/SetSavingsGoalCommandTest.java
  src/test/java/seedu/finbro/logic/command/TrackBudgetCommandTest.java
  src/test/java/seedu/finbro/logic/command/TrackSavingsGoalCommandTest.java
  src/test/java/seedu/finbro/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, type.Task, priority.High

#100 Update EXPECTED.TXT
  text-ui-test/EXPECTED.TXT
Labels: priority.High
