Repository AY2425S2-CS2113-W13-3/tp, pull requests merged in 2025-04, with the labels that each got.

#101 Quick Updates
  docs/UserGuide.md
  src/main/java/seedu/finbro/logic/command/EditCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/test/java/seedu/finbro/logic/command/EditCommandTest.java
  src/test/java/seedu/finbro/logic/command/SummaryCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#102 New input
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement

#103 Adds to UG, DG, and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ljunfun.md
  src/test/java/seedu/finbro/logic/command/BalanceCommandTest.java
Labels: type.Enhancement

#104 Adds ExceptionsTest and ParserPrivateMethodTest
  src/main/java/seedu/finbro/logic/command/EditCommand.java
  src/test/java/seedu/finbro/logic/exceptions/ExceptionsTest.java
  src/test/java/seedu/finbro/parser/ParserPrivateMethodsTest.java
Labels: type.Enhancement

#106 Add many updates
  docs/README.md
  docs/UserGuide.md
  src/main/java/seedu/finbro/logic/command/HelpCommand.java
  src/main/java/seedu/finbro/storage/Storage.java
  src/test/java/seedu/finbro/logic/command/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#107 pdfs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/pdf/DeveloperGuide.pdf
  docs/pdf/UserGuide.pdf
Labels: type.Enhancement

#110 v2.0
  README.md
  docs/diagrams/mermaid/class/architecture.mermaid
  docs/diagrams/mermaid/class/command-budget-class.mermaid
  docs/diagrams/mermaid/class/command-class.mermaid
  docs/diagrams/mermaid/class/command-detail-class.mermaid
  docs/diagrams/mermaid/class/exceptions-class.mermaid
  docs/diagrams/mermaid/class/main-class.mermaid
  docs/diagrams/mermaid/class/model-class.mermaid
  docs/diagrams/mermaid/class/parser-class.mermaid
  docs/diagrams/mermaid/class/parser-detail-class.mermaid
  docs/diagrams/mermaid/class/storage-class.mermaid
  docs/diagrams/mermaid/class/storage-detail-class.mermaid
  docs/diagrams/mermaid/class/transaction-class.mermaid
  docs/diagrams/mermaid/class/ui-class.mermaid
  docs/diagrams/mermaid/class/ui-detail-class.mermaid
  docs/diagrams/mermaid/sequence/sequence-add-transaction.mermaid
  docs/diagrams/mermaid/sequence/sequence-balance.mermaid
  docs/diagrams/mermaid/sequence/sequence-edit.mermaid
  docs/diagrams/mermaid/sequence/sequence-filter.mermaid
  docs/diagrams/mermaid/sequence/sequence-list.mermaid
  docs/diagrams/mermaid/sequence/sequence-search.mermaid
  docs/diagrams/mermaid/sequence/sequence-summary.mermaid
  docs/diagrams/puml/class/command-budget-class.puml
  docs/diagrams/puml/class/command-class.puml
  docs/diagrams/puml/class/command-detail-class.puml
  docs/diagrams/puml/class/exceptions-class.puml
  docs/diagrams/puml/class/main-class.puml
  docs/diagrams/puml/class/model-class.puml
  docs/diagrams/puml/class/parser-class.puml
  docs/diagrams/puml/class/parser-detail-class.puml
  docs/diagrams/puml/class/storage-class.puml
  docs/diagrams/puml/class/storage-detail-class.puml
  docs/diagrams/puml/class/transaction-class.puml
  docs/diagrams/puml/class/ui-class.puml
  docs/diagrams/puml/class/ui-detail-class.puml
  docs/diagrams/puml/sequence/sequence-add-transaction.puml
  docs/diagrams/puml/sequence/sequence-balance.puml
  docs/diagrams/puml/sequence/sequence-edit.puml
  docs/diagrams/puml/sequence/sequence-filter.puml
  docs/diagrams/puml/sequence/sequence-list.puml
  docs/diagrams/puml/sequence/sequence-search.puml
  docs/diagrams/puml/sequence/sequence-summary.puml
  src/main/java/seedu/finbro/LoggingConfig.java
  src/main/java/seedu/finbro/logic/command/SetBudgetCommand.java
  src/main/java/seedu/finbro/storage/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#115 Adds to DG and PPP
  docs/DeveloperGuide.md
  docs/team/ljunfun.md
Labels: type.Task

#116 Update DG & PPP
  docs/DeveloperGuide.md
  docs/team/notgiggs.md
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#171 Fix 17 bugs
  docs/UserGuide.md
  src/main/java/seedu/finbro/logic/command/BalanceCommand.java
  src/main/java/seedu/finbro/logic/command/ListCommand.java
  src/main/java/seedu/finbro/logic/command/SummaryCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/Expense.java
  src/main/java/seedu/finbro/model/Income.java
  src/main/java/seedu/finbro/ui/Ui.java
  src/main/java/seedu/finbro/util/CurrencyFormatter.java
  src/test/java/seedu/finbro/logic/command/BalanceCommandTest.java
  src/test/java/seedu/finbro/logic/command/ListCommandTest.java
  src/test/java/seedu/finbro/logic/command/SummaryCommandTest.java
  src/test/java/seedu/finbro/model/ExpenseTest.java
  src/test/java/seedu/finbro/model/IncomeTest.java
  src/test/java/seedu/finbro/model/TransactionTest.java
  src/test/java/seedu/finbro/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#172 Fix 4 bugs
  src/main/java/seedu/finbro/logic/command/ExportCommand.java
  src/main/java/seedu/finbro/logic/command/SummaryCommand.java
  src/main/java/seedu/finbro/logic/command/TrackSavingsGoalCommand.java
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/test/java/seedu/finbro/logic/command/SummaryCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#178 Fix/bugs
  docs/DeveloperGuide.md
  src/main/java/seedu/finbro/logic/command/ClearCommand.java
  src/main/java/seedu/finbro/model/TransactionManager.java
  src/test/java/seedu/finbro/logic/command/ClearCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#180 Branch fix list bugs
  docs/UserGuide.md
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#181 fix png problem
  docs/DeveloperGuide.md
  docs/diagrams/mermaid/class/command-class.mermaid
  docs/diagrams/mermaid/class/command-detail-class.mermaid
  docs/diagrams/mermaid/class/command-v1.mermaid
  docs/diagrams/mermaid/class/command-v2.mermaid
  docs/diagrams/mermaid/class/exceptions-class.mermaid
  docs/diagrams/mermaid/class/parser-class.mermaid
  docs/diagrams/mermaid/class/parser-detail-class.mermaid
  docs/diagrams/mermaid/class/parser-to-command.mermaid
  docs/diagrams/mermaid/class/storage-class.mermaid
  docs/diagrams/mermaid/class/storage-detail-class.mermaid
  docs/diagrams/mermaid/class/ui-class.mermaid
  docs/diagrams/mermaid/class/ui-detail-class.mermaid
  docs/diagrams/puml/sequence/sequence-add-transaction.puml
  docs/diagrams/puml/sequence/sequence-balance.puml
  docs/diagrams/puml/sequence/sequence-edit.puml
  docs/diagrams/puml/sequence/sequence-filter.puml
  docs/diagrams/puml/sequence/sequence-list.puml
  docs/diagrams/puml/sequence/sequence-search.puml
  docs/diagrams/puml/sequence/sequence-summary.puml
  docs/img/mermaid/architecture.png
  docs/img/mermaid/command-v1.png
  docs/img/mermaid/command-v2.png
  docs/img/mermaid/exceptions-class.png
  docs/img/mermaid/main-class.png
  docs/img/mermaid/model-class.png
  docs/img/mermaid/parser-class.png
  docs/img/mermaid/parser-detail-class.png
  docs/img/mermaid/parser-to-command.png
  docs/img/mermaid/storage-class.png
  docs/img/mermaid/storage-detail-class.png
  docs/img/mermaid/ui-class.png
  docs/img/mermaid/ui-detail-class.png
  docs/img/puml/sequence-add-transaction.png
  docs/img/puml/sequence-balance.png
  docs/img/puml/sequence-edit.png
  docs/img/puml/sequence-filter.png
  docs/img/puml/sequence-list.png
  docs/img/puml/sequence-search.png
  docs/img/puml/sequence-summary.png
Labels: type.Task

#182 Fixes improper variable name
  src/main/java/seedu/finbro/logic/parser/Parser.java
Labels: type.Bug

#186 fix date validation
  docs/team/alaneel.md
  src/main/java/seedu/finbro/logic/parser/Parser.java
  src/main/java/seedu/finbro/ui/Ui.java
  src/main/java/seedu/finbro/util/DateUtil.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#188 Quick fixes
  src/main/java/seedu/finbro/logic/parser/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#192 Update DeleteCommand and UI
  src/main/java/seedu/finbro/logic/command/DeleteCommand.java
  src/main/java/seedu/finbro/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#196 Update notgiggs.md
  docs/team/notgiggs.md
Labels: priority.High
